### ISSUE TITLE
won't mount/unmount owncloud

### ISSUE THREAD

**Issue by ForSquirel** [yoichiro/chromeos-filesystem-webdav#10]
Connecting to owncloud webdav works fine initially. Closed computer to sleep and when tried to access files in the morning WEBDAV popped up a notification error that action was taking to long. Trying to unmount from the files app doesn't work, and trying to remount it through WEBDAV app states it's already mounted. Now I am unable to access remote files without signing out/reboot.

Running on a Samsung Exynos chromebook

**Comment by yoichiro** [comment]
@ForSquirel I modified the resuming logic. At least, I forgot adding the definitely needed function to handle the error. Also, if resuming failed, I removed the code to unmount so that users can mount again after the network works again. In this version 1.0.2, this issue will be fixed. Thank you for the reporting!

**Comment by yoichiro** [comment]
@ForSquirel I have just released the new version 1.0.2 including the diff #13 to fix this issue.
