### ISSUE TITLE
Mount a new WebDAV Server (Synology NAS)

### ISSUE THREAD

**Issue by lenayres** [yoichiro/chromeos-filesystem-webdav#22]
I am trying to mount my Synology NAS DS212J to my Chromebook so the file structure shows up in the File Manager, similar to my Google Drive files.  I have enabled WebDAV on my NAS.  When I attempt to use the app for mounting my NAS, it returns"NOT_FOUND".  I am able to log into my NAS from my Chromebook and view the URL to insure it matches.  If the URL isn't found, is it possible that the format of the URL entered is incorrect?  I attempted to use several formats for the URL, including the following:
192.168.1.xxx (my local IP address)
192.168.1.xxx:5005 (my local IP address and WebDAV port)
My Synology QuickConnect name
My DDNS link
My WAN IP address

None of those formats worked.  What am I doing wrong or how do I get it to mount?

**Comment by Vmeup** [comment]
I had a similar issue with creating a WebDav connection with my Synology Server as well. I found that I needed to add the http:// in order to make it work. ie. http://xxx.xxx.xxx:5005 

I haven't had any luck mounting with a SSL connection via https:// yet though. I will be reaching out for help on this in a separate thread. 

Good luck

**Comment by lenayres** [comment]
Thanks. Adding the prefix of http:// worked immediately, and I was able to mount my Synology NAS to my Chromebook and view from File Manager.
