### ISSUE TITLE
box.com NOT_FOUND during login

### ISSUE THREAD

**Issue by KeithWalters** [yoichiro/chromeos-filesystem-webdav#8]
I have tried to use this against https://dav.box.com/dav and on entering username and password it returns:

NOT_FOUND

Using a REST client I have confirmed that the PROPFIND request against this URL with basic auth successfully returns a <d:multistatus.../> XML.

Can anyone get this to work against box.com?

**Comment by yoichiro** [comment]
@KeithWalters Thank you for the reporting. Yes, I already found this issue. So, I have just released the new bug fix version 1.0.1 to solve this issue. The diff was #7.

Probably, its new version will be deliveried to your Chromebook/box in a few minutes. Could you confirm whether this issue is fixed or not with the version 1.0.1?

**Comment by KeithWalters** [comment]
Hi @yoichiro - amazing fast response.  I'll let you know once it updates and have tried it!

**Comment by KeithWalters** [comment]
1.0.1 delivered, worked a charm @yoichiro - thank you!

**Comment by yoichiro** [comment]
@KeithWalters It's my pleasure.

**Comment by martinwdubois** [comment]
Hello, I'm able to mount onedrive on my chromebook. But when I try to access it using the file manager I get the spinning circle forever... What's wrong?

Thanks for your efforts in making Chrome OS work with other cloud storage.
Martin
